version: '3'

services:
  my_redis:
    image: redis:latest
    ports:
      - 6379:6379
  picture-api:
    image: kgh2120/picture-api:alpha
    ports:
      - 8080:8080
    depends_on:
      - my_redis
