version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  picture-api:
    image: kgh2120/picture-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis