spring:
  profiles:
    group:
      "default": "dev"
  config:
    import:
      - mailSender.yml
      - secret.properties
  datasource:
    hikari:
      connection-timeout: 7000
  cache:
    type: redis
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

quiz:
  limit : 12
server:
  tomcat:
    max-swallow-size: 20MB
