spring:
  profiles:
    group:
      "default": "dev"
  config:
    import:
      - mailSender.yml
      - secret.properties
  datasource:
    hikari:
      connection-timeout: 7000
  cache:
    type: redis

quiz:
  limit : 12

