name: ci for main and deploy to ec2

on:
  push:
    branches: 
      - main

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/trading
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create mailSender.yml
        env:
          SECRET_CODE: ${{ secrets.MAILSENDER }}
          SECRET_DIR: src/main/resources
          SECRET_FILE_NAME: mailSender.yml
        run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

      - name: Create secret.properties
        env:
          SECRET_CODE: ${{ secrets.SECRET }}
          SECRET_DIR: src/main/resources
          SECRET_FILE_NAME: secret.properties
        run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

      - name: Create application-prod.yml
        env:
          SECRET_CODE: ${{ secrets.PROD_PROPERTIES }}
          SECRET_DIR: src/main/resources
          SECRET_FILE_NAME: application-prod.yml
        run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
        
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: . 			# dockerfile이 있는 위치랑 맞춰주자
          file: ./Dockerfile	# 빌드할 Dockerfile이 있는 디렉토리
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, cicd ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker-compose -f docker-compose.yml stop && docker-compose -f docker-compose.yml rm
          docker-compose -f docker-compose.yml up -d
